#.github/workflows/basic.yaml
name: task - validate commit on android-appcompat
on:
  push:
    branches: [ android-appcompat ]

jobs:
  basic_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup actions.
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
# 修复 ./gradlew: Permission denied 这个问题
      - name: Make gradlew executable
        run: chmod +x ./gradlew

        # lint 检查
      - name: Check lint
        if: always()
        run: ./gradlew lint

      - name: Run Unit Tests
        if: always()
        run: ./gradlew testDebugUnitTest
        
        
# 执行编译
      - name: Generate AAR and APK files
        if: always()
        run: ./gradlew assembleDebug
# 执行上传文件 actions/upload-artifact@v2是一个
      - name: Upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts.zip
          path: |
            app/build/outputs/apk/debug/app-debug.apk